services:
  backend:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config.toml:/usr/src/app/config.toml
  frontend:
    build:
      context: frontend/
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "9863:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
volumes:
  db-data:
